# Generated by Django 5.2 on 2025-09-23 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_transaction_usuario_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imagen',
        ),
    ]
